Removed unused RunSequence from gulpfile.js and fixed a small typo in index.html
meetjspl/summit pull request #13
Opened 2017-05-26 10:54 UTC by tomaszlakomygp

In the pursuit of getting a free meet.js summit ticket (:onion:) I've taken a quick look through the codebase and I've noticed that `runSequence` is imported in `gulpfile.js` and is not used at all. I've also fixed a small typo in `index.html`

2017-05-26 11:03 UTC, feimosi commented on src/index.html
> +          major business hubs in the country (Gdańsk, Warsaw, Kraków, Poznań, Wroclaw, Łodz, Katowice,
_Wrocław_
_Łódz_
:slightly_smiling_face:

2017-05-26 11:05 UTC, tomaszlakomygp commented on src/index.html
> +          major business hubs in the country (Gdańsk, Warsaw, Kraków, Poznań, Wroclaw, Łodz, Katowice,
Good point 👍

2017-05-26 11:10 UTC, tomaszlakomygp commented
On the other hand, Warsaw and Cracow are waaay more familiar for foreigners so perhaps they should both remain in English? 🤔

2017-05-26 12:02 UTC, feimosi commented
I agree, Warsaw and Cracow are more 'foreigners-friendly' names.

2017-05-26 13:33 UTC, mmiszy commented
Why change Cracow to Kraków but keep Warsaw instead of Warszawa? It's either one way or another and personally I think we should go with Warsaw and Cracow.

2017-05-26 13:34 UTC, mmiszy commented
Is it possible to remove `run-sequence` from `package.json` too?

2017-05-26 15:09 UTC, typeofweb requested changes
See my comments

2017-05-29 08:33 UTC, tomaszlakomygp commented
@mmiszy comments addressed 👍

2017-05-29 08:38 UTC, lukaszklis approved these changes

2017-05-29 08:39 UTC, merged