[SUMMIT] - Add new speakers
meetjspl/summit pull request #93
Opened 2022-08-13 16:08 UTC by Illya1074

2022-08-16 16:30 UTC, JKrymarys requested changes
I think that you looked at the wrong row :P In comments I added the proper titles and messages

2022-08-16 16:30 UTC, JKrymarys commented on src/index.html
> +                  <h4>Advanced TypeScript</h4>
Is it worth learning Vue in 2022 and why not?

2022-08-16 16:30 UTC, JKrymarys commented on src/index.html
> +                    TypeScript become extremely popular tool but how well you know him? Probably you
This is not another introduction to the Vue. I'm gonna focus on differences between Vue, React and Angular in topics like: e.g.: communication, forms, storage, testing. All with code examples. Base on that I'll tell when Vue will be good choose and why invest time in learning it isn't good idea.

2022-08-16 16:30 UTC, JKrymarys commented on src/index.html
> +                  <p class="talks-box__desc">
Have you ever played Mario Bros?

Let's drop our adult belief that playing is something frivolous and a waste of time.

Let's have fun, write the game in JS/React
topics:
🍄 the technique of creating gravity
👨🏻 player creation
🕹️ platforms
🐢 parallax effect
⭐ level creation

2022-08-16 16:30 UTC, JKrymarys commented on src/index.html
> +                  <h4>Our approach to unifying company products with shareable library</h4>
How to make an engine for a side scroller video game using HTML5 Cavnas and React

2022-08-18 18:06 UTC, naugtur commented
To nadal wisi z pomieszanymi opisami? :open_mouth:

2022-08-18 18:18 UTC, merged